### ISSUE TITLE
broadcast message frequency of 'x players not ready' could be reduced

### ISSUE THREAD

**Issue by jxsl13** [ddnet-insta/ddnet-insta#105]
broadcast message frequency of 'x players not ready' could be reduced

I just looked at f1 console in order to read chat history and that message was there quite often.
I think the broadcast message has a timeout of how long it is visible, does it?
So instead of sending the message every second, it could be reduced to that timeout period (-1 second).

Joining players would then need to wait that period to receive that broadcast as well or they would receive it immediately when joining in case that the broadcast condition still holds true.

**Comment by ChillerDragon** [comment]
BTW there is `cl_print_broadcasts 0`
