### ISSUE TITLE
Results - Clan bugged

### ISSUE THREAD

**Issue by lukure** [ddnet-insta/ddnet-insta#110]
We have already received some results in a 3on3 where a clan name was displayed that only 1 player of the team had

**Comment by ChillerDragon** [comment]
@M0REKZ sos

**Comment by M0REKZ** [comment]
> @M0REKZ sos

Thats from #109 by @Anime-pdf 🥶

**Comment by ChillerDragon** [comment]
Omg wrong ping you are right :sweat_smile:

**Comment by Anime-pdf** [comment]
Will take a look today 😭
