### ISSUE TITLE
bug - master server registration is seemingly broken on the latest master commit

### ISSUE THREAD

**Issue by jxsl13** [ddnet-insta/ddnet-insta#114]
I compiled the latest master commit 38c131fe411787b93b864d973d252d0ebb97f480 and the server was unable to communicate with the master server in order to register itself:

Then I rolled back my version to 44666c21f76cfe6a9cbee16f5ab44ab592662bcd which seems to work.
Those 0.7 compatibility PRs from upstream ddnet seem to have broken server registration.

Explicitly the 0.6.x ddnet master server registration seems to be broken..

**Comment by ChillerDragon** [comment]
Fixed in https://github.com/ddnet/ddnet/pull/8725
