### ISSUE TITLE
Vanilla pickups ignore speeder tiles

### ISSUE THREAD

**Issue by M0REKZ** [ddnet-insta/ddnet-insta#118]
if i put sv_gametype into ddnet pickups actually moves, but on vanilla gametypes they just stay in place

**Comment by ChillerDragon** [comment]
https://github.com/user-attachments/assets/2acba279-5087-410e-8c1e-c73decda2aab

You wanted this right? I might have ripped out all ddrace stuff from the vanilla pickups intentionally but yes that move feature is pretty cool.

**Comment by M0REKZ** [comment]
Yeah thats what i wanted thanks, i also noticed an issue with switch entities, they work as they were in the Game layer, as i'm telling this here idk if it's worth to make a new github issue for this xd

**Comment by ChillerDragon** [comment]
@M0REKZ yes yes make as many issues as you want. Comments in closed issues get los.

**Comment by ChillerDragon** [comment]
Oh and when you open an issue please include some steps to reproduce or an image because for me the switches look fine in entities @M0REKZ
