### ISSUE TITLE
Switches are not working

### ISSUE THREAD

**Issue by M0REKZ** [ddnet-insta/ddnet-insta#119]
As you can see plasma gun is not getting deactivated even if i touch the switch tile multiple times, i noticed that the problem is the missing `Number` parameter when calling gamecontroller's `OnEntity` inside base_vanilla and base_instagib

![switches](https://github.com/user-attachments/assets/ed70e055-fae0-4784-807e-50986b877165)

**Comment by ChillerDragon** [comment]
Thanks for debugging this
