### ISSUE TITLE
Antiping prediction bugs

### ISSUE THREAD

**Issue by M0REKZ** [ddnet-insta/ddnet-insta#120]
(Need to have antiping enabled)

if you stay near a shield with a grenade, antiping thinks that it gets removed and it shows a hammer

![antiping](https://github.com/user-attachments/assets/18984794-f29c-49d7-97eb-346603b5e5fa)

also when shooting without ammo antiping still predict explosion force if you shoot the floor

if i remember correctly, the first thing is solvable by removing one of the PREDICT_DDRACE gameflags (dont remember which one) but that also could break stopper prediction, so idk what is the best.

**Comment by ChillerDragon** [comment]
Seems like we need to get a PREDICT_VANILLA_PICKUPS flag into the ddnet client. The bug from the gif is fixed now. For ddrace tile prediction support I will open an issue upstream because that can not be done on the server side.
