### ISSUE TITLE
stats: dm and ctf decide on what to track

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet-insta/ddnet-insta#158]
I am slowly finalizing the stats feature. Now the question is what do we need to track in the database. What is interesting for rankings? I would like to keep it clean and minimal and not track every single possible metric but only the things users might actually care about.

Here is what is currently tracked for dm. Are you missing something @PathosEthosLogos @M0REKZ @Anime-pdf @gerdoe-jr?

```
> select * from dm;
+-----------------+---------------------+--------+-------+--------+-------+------+--------+-------------+-----------+-----------+
| name            | first_seen          | points | kills | deaths | spree | wins | losses | shots_fired | shots_hit | wallshots |
+-----------------+---------------------+--------+-------+--------+-------+------+--------+-------------+-----------+-----------+
| ChillerDragon   | 2024-09-25 12:16:09 |     13 |    12 |      0 |    11 |    1 |      0 |          54 |        33 |         2 |
| ChillerDragon.* | 2024-09-25 12:16:09 |      0 |     0 |     12 |     0 |    0 |      1 |           0 |         0 |         0 |
+-----------------+---------------------+--------+-------+--------+-------+------+--------+-------------+-----------+-----------+
```

The hammer is excluded from shots fired and shots hit (https://github.com/ddnet-insta/ddnet-insta/issues/150).
All weapons are tracked together in shots fired and shots hit. I would like to keep it like that for simplicity. Or does someone really need something like a ``/top5laser_hits`` ranking command?

Here is what is currently tracked for ctf. Same as dm plus 3 more flag columns.

```
> select * from ctf;
+-----------------+---------------------+--------+-------+--------+-------+------+--------+-------------+-----------+-----------+------------+---------------+---------------+
| name            | first_seen          | points | kills | deaths | spree | wins | losses | shots_fired | shots_hit | wallshots | flag_grabs | flag_captures | flagger_kills |
+-----------------+---------------------+--------+-------+--------+-------+------+--------+-------------+-----------+-----------+------------+---------------+---------------+
| ChillerDragon   | 2024-09-25 12:23:15 |      0 |     0 |      0 |     0 |    0 |      0 |           0 |         0 |         0 |          0 |             0 |             0 |
| ChillerDragon.* | 2024-09-25 12:23:15 |      0 |     0 |      0 |     0 |    0 |      0 |           0 |         0 |         0 |          0 |             0 |             0 |
+-----------------+---------------------+--------+-------+--------+-------+------+--------+-------------+-----------+-----------+------------+---------------+---------------+
```

**Comment by M0REKZ** [comment]
Maybe hook kills could be tracked too (since there is already configs like `sv_only_hook_kills`)

**Comment by ChillerDragon** [comment]
> Maybe hook kills could be tracked too (since there is already configs like `sv_only_hook_kills`)

Would you be interested in a chat command like ``/top5hook_kills`` or why would you think it is interesting to track?

**Comment by M0REKZ** [comment]
Hooking players is not always easy, specially with high ping xD, so it may be something that actually requires some "skill"

**Comment by M0REKZ** [comment]
although it may fit better on instagib tables

**Comment by Anime-pdf** [comment]
Maybe `fastest_capture` for ctf, I remember hardliner's insta tracked this, sounds interesting to me

**Comment by ChillerDragon** [comment]
@Anime-pdf yea that will be tracked in its own table to have the times per map.

**Comment by ChillerDragon** [comment]
@M0REKZ sorry I decided against tracking hooks. Thanks for your input tho.

Its been a week. The servers are already live with those columns. I do not think anything is missing. No new columns added.
