### ISSUE TITLE
Bug: Checkboxes wrong mark if config has similar names

### ISSUE THREAD

**Issue by M0REKZ** [ddnet-insta/ddnet-insta#188]
Note that i didnt touch the anticamper type

<img width="482" alt="screen" src="https://github.com/user-attachments/assets/1883dd74-747e-4a46-b343-4acd516d9363">
<img width="445" alt="scren2" src="https://github.com/user-attachments/assets/c5f794fe-c7f0-4c7a-a927-1f8f3e0c45b0">

**Comment by ChillerDragon** [comment]
could you show me your config?

**Comment by M0REKZ** [comment]
add_vote "[ ] Anticamper: ON" sv_anticamper 1
add_vote "[ ] Anticamper: OFF" sv_anticamper 0
add_vote "[ ] Anticamper Kills Player" sv_anticamper_freeze 0
add_vote "[ ] Anticamper Freezes Player" sv_anticamper_freeze 5

**Comment by ChillerDragon** [comment]
Thanks. I can reproduce. That indeed looks like a bug. I will investigate.
