### ISSUE TITLE
At specific conditions horizontal DDrace doors dont have collision

### ISSUE THREAD

**Issue by M0REKZ** [ddnet-insta/ddnet-insta#201]
Try to collide with the 2cnd door in this map:
[doorbug.map.zip](https://github.com/user-attachments/files/18242031/doorbug.map.zip)

This bug is ddnet-insta only and does not happen on mainstream DDNet

Seems that the First Door has to be vertical to reproduce or that should be two doors in the first switch number, idk need investigation

**Comment by ChillerDragon** [comment]
I can reproduce, thanks for reporting.

https://github.com/user-attachments/assets/73774cc1-4b97-40da-b639-e1be054ce3fd

**Comment by ChillerDragon** [comment]
I found the issue. Fng spikes use the index 9 which is shared with freeze.

https://github.com/ddnet-insta/ddnet-insta/blob/fa11e48c8921dfcda264e892aefeabafb1a23187/src/game/collision.cpp#L324-L327

I had to let them through in collision.cpp to make them work. Hopefully there is another way I will investigate. In general freeze overlapping with fng tiles sounds a bit annoying. Makes me rethink https://github.com/ddnet-insta/ddnet-insta/issues/79. Currently fngores is not possible which would be nice. But then the ddnet client can not show the correct fng entities if ddnet-insta uses the non standard spike indecies.

Another question is why are switchers not allowed to overlap with other tiles in the ddnet. In S-DDRace for example you can place switch doors in collision tiles and cleanly hide the door in the wall if it is open. If ddnet would allow switch tile overlapping then ddnet-insta would just work again without making any changes.

I am not sure how fast I can come up with a clean solution for this. @M0REKZ as a hotfix you could remove the freeze tiles under the door tiles or remove [those lines](https://github.com/ddnet-insta/ddnet-insta/blob/fa11e48c8921dfcda264e892aefeabafb1a23187/src/game/collision.cpp#L324-L327) and break fng.

**Comment by ChillerDragon** [comment]
Never mind finding a good fix was easy :partying_face:
