### ISSUE TITLE
Use chat messages "pause" and "stop" to stop the game?

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet-insta/ddnet-insta#66]
Not sure but should "pause" and "stop" be an alias for /pause and the 0.7 ready change net message?
Should probably also include "go" then.

Should be case insensitive.

Not sure if it is good or bad tho. Rilla said it is not needed. I saw it used twice in the gctf tournament by people who wanted to stop the game. And then others used their pause binds to actually pause it.

I remember the vanilla scene back in the days used the chat messages "stop" and "go at xx" which was the code for all players to just stop moving manually. Some OG players might have "stop" muscle memory. Not sure how other pvp mods do it. I remember vaguely that you mentioned something like that @JSaurusRex what do you think?

What are the possible drawbacks? Unwanted game pauses when someone says "stop" and did not mean to pause the game but tell someone to stop doing something.

The majority of gctf players also has a /pause bind from ddrace that already works. Maybe it just needs more marketing instead of encouraging people starting to also bind the "stop" chat message.

**Comment by lukure** [comment]
/pause and /go were also used in 0.7 gCTF to pause/start the game.

**Comment by JSaurusRex** [comment]
I wanted to add this as an server side option for ictf, ictf players are used to stop and go commands so its not really a problem
You could make them aliases for.
However you gotta make sure you only check for !stop /stop or stop, and not stop anywhere in the message.
Anyway I'll make a pr for it and we'll see how everybody likes it.

**Comment by ChillerDragon** [comment]
I added ``sv_stop_and_go_chat`` it is off by default. When activated it acts like a forced ready change. If anyone writes the full match "pause", "stop", "go" or "start" in the chat it will pause or unpause the game no matter what.

If the game was paused with a ready change it can be force started with a "go" even if not everyone is ready. If i game is paused with "pause" it can still be started if everyone sends a ready change given that ``sv_player_ready_mode`` is active too.

Also the ``sv_countdown_unpause`` works for "go" and "start". With these 3 configs server admins can now fully customize what they want.
