### ISSUE TITLE
Gametype naming iFNG, gFNG, iDM, gDM, iZcatch, gZcatch

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet-insta/ddnet-insta#97]
So far all fng mods I know are called it "fng", "boomfng" and "openfng" and so on. But what if we called it "iFNG" "gFNG" and use that concept for all future modes. If the game mode name starts with "i" its laser if it starts with "g" its grenade. And that prefix has to be there. Even for zCatch. That one would become gZcatch and iZcatch. Which looks super unnatural but it would be consistent and obvious to the users what this gametype is about.

I think we should use the chance of having one repository for multiple instagib based modes to enforce one consistent naming convention. Here are two ideas that come to my mind. One is taking the original gametype names that were used by other code bases and the other is using i and g prefix for everything.

# stay close to the original names

Problem with that is that they are not consistent and one can not tell which weapon is being played if the mode is called "zCatch" or "fng"

- iDM
- gDM
- iTDM
- gTDM
- fng
- solofng
- boomfng
- bolofng
- zCatch

# i and g prefix

Problem with that is that "i" = laser is not obvious. "i" stands for instagib and could technically be any weapon so thats wrong. Also what about other weapons? Do we ever want to add zCatch playable with gun instead of laser and grenade? Or modes with more weapons https://github.com/ZillyInsta/ddnet-insta/issues/53?

So the format would be [ig][T]?[name]

- iDM
- gDM
- iFNG
- gFNG
- iTFNG
- gTFNG
- iZcatch
- gZcatch

Game server marketing wise "iTFNG" instead of "fng" is horrible. But it has to say "i" instagib "T" team fng to follow the convention.

**Comment by M0REKZ** [comment]
It could be kinda confusing for the ones that are used to those names, however, maybe it would be good as a "prefix standard" and be more intuitive for new players.

Also, i dont think the "T" as a prefix is really necessary, for example: "Last Team Standing" (LTS) does not have the "T" as a prefix, otherwise it would be "TLMS" and that is kinda weird.

**Comment by ChillerDragon** [comment]
Lets stay close to the original names. I went with zCatch and grenade and laser share the same game controller and game type. There is now a `sv_spawn_weapons` which is a bit unrelated to the current game mode so it should not be in the name anyways. So fng will be: fng, bolofng, boomfng, solofng
